baseURL = "https://www.frankspin.nl"
languageCode = "nl-nl"
title = "Frank Spin"
theme = "frank"


MetaDataFormat = "yaml"
DefaultContentLanguage = "nl"
SectionPagesMenu = "main"enableRobotsTXT = false
background_color_class = "white"
googleAnalytics = "UA-110086332-1"
